// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-qQWr1mLdEAhMV3E98yNZgkJeXEIyJo8',
    appId: '1:536038361778:web:1bb75bb8477002fd7d57ab',
    messagingSenderId: '536038361778',
    projectId: 'flash-chat-31d5f',
    authDomain: 'flash-chat-31d5f.firebaseapp.com',
    storageBucket: 'flash-chat-31d5f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwFqbQQ3jB7BS186eMHsLpUmyZYGcjOtk',
    appId: '1:536038361778:android:69a9e3fd8ca80f837d57ab',
    messagingSenderId: '536038361778',
    projectId: 'flash-chat-31d5f',
    storageBucket: 'flash-chat-31d5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTDiFYG5jqerAawkspMEf_UFV5hEUXtMg',
    appId: '1:536038361778:ios:a5fb45dc833922f27d57ab',
    messagingSenderId: '536038361778',
    projectId: 'flash-chat-31d5f',
    storageBucket: 'flash-chat-31d5f.firebasestorage.app',
    iosBundleId: 'com.example.flashChatStartingProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTDiFYG5jqerAawkspMEf_UFV5hEUXtMg',
    appId: '1:536038361778:ios:a5fb45dc833922f27d57ab',
    messagingSenderId: '536038361778',
    projectId: 'flash-chat-31d5f',
    storageBucket: 'flash-chat-31d5f.firebasestorage.app',
    iosBundleId: 'com.example.flashChatStartingProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-qQWr1mLdEAhMV3E98yNZgkJeXEIyJo8',
    appId: '1:536038361778:web:beaf0077d0c04f347d57ab',
    messagingSenderId: '536038361778',
    projectId: 'flash-chat-31d5f',
    authDomain: 'flash-chat-31d5f.firebaseapp.com',
    storageBucket: 'flash-chat-31d5f.firebasestorage.app',
  );
}
